// <auto-generated />
namespace HumanResourcesManagementBackend.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addRealtion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addRealtion));
        
        string IMigrationMetadata.Id
        {
            get { return "202308181546263_addRealtion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
